In [3]:
# Load kedro environment (not needed in .py)
from pathlib import Path
from kedro.framework.context import load_context

# Load a context to be able to work in the notebook
#current_dir = Path.cwd()
current_dir = Path("/u01/share/cesar/aa_engine_uy/notebooks/")
proj_path = current_dir.parent
context = load_context(proj_path)
catalog = context.catalog
credentials = context.config_loader.get("credentials*","credentials*/**")
parameters = context.config_loader.get("parameters*","parameters*/**")

from aa_engine_pkg.assets.utils import *
from aa_engine_pkg.assets.core.data.kedro.catalog_expansion.partitioned_sql import SQLPartitionedDataSet
from datetime import datetime

In [2]:
upgrades=catalog.load('upgrades_basicos')

2021-01-08 15:07:52,048 - kedro.io.data_catalog - INFO - Loading data from `upgrades_basicos` (SQLPartitionedDataSet)...

In [ ]:
def prod_moves(upgrades:SQLPartitionedDataSet,aniomes:str):
    start_date=pd.to_datetime(aniomes+"01")
    end_date = start_date + relativedelta(months=1) - timedelta(days=1)
    start_date=start_date.strftime('%Y%m%d')
    end_date=end_date.strftime('%Y%m%d')
    print(start_date, "|",end_date)
    # Load data for required period
    df_prod_change = upgrades.filter_by(date=[start_date,end_date])
    
    df_prod_change=df_prod_change.loc[df_prod_change.EVENTO_ID.isin([107,108])].sort_values(['CUSTOMER_ID','FECHA'])
    
    df_prod_change=df_prod_change.groupby('CUSTOMER_ID').head(2)
    
    old=df_prod_change.loc[df_prod_change.EVENTO_ID==107]
    new=df_prod_change.loc[df_prod_change.EVENTO_ID==108]
    movs=pd.merge(old,new,on="CUSTOMER_ID",how="left")
    
    movs=movs[["CUSTOMER_ID","PRODUCTO_x","PRODUCTO_y"]]
    path=f'/u01/share/cesar/others/upsell_uy/{aniomes}'
    movs.to_parquet(path)

In [8]:
aniomes="202001"

20200101 | 20200131

In [10]:
# Load data for required period
df_prod_change = upgrades.filter_by(date=[start_date,end_date])

select * from stg_uy_plan_evento where PROD_CATEGORY_ID = 3 and EVENTO_ID IN (107,108,133,142) and FECHA >= to_date('20200101', 'yyyymmdd') and FECHA < to_date('20200131', 'yyyymmdd')

In [12]:
df_prod_change.head()

,CUSTOMER_ID,EVENTO_ID,EVENTO,PRODUCTO_ID,PRODUCTO,PROD_CATEGORY_ID,PROD_CATEGORY,FECHA,REASON,DATE_EXP
0,55427965,142,Cancel Product,139,DIRECTV ORO HD ONLY,3,Basico,2020-01-24 16:26:23,108,202001
1,54859997,142,Cancel Product,139,DIRECTV ORO HD ONLY,3,Basico,2020-01-10 17:24:49,108,202001
2,54898702,142,Cancel Product,139,DIRECTV ORO HD ONLY,3,Basico,2020-01-01 03:03:35,28,202001
3,54994901,133,Disconnect Product,139,DIRECTV ORO HD ONLY,3,Basico,2020-01-15 12:41:26,123,202001
4,54995531,133,Disconnect Product,139,DIRECTV ORO HD ONLY,3,Basico,2020-01-15 12:41:26,123,202001

In [26]:
df_prod_change=df_prod_change.loc[df_prod_change.EVENTO_ID.isin([107,108])].sort_values(['CUSTOMER_ID','FECHA'])

In [27]:
df_prod_change.head()

,CUSTOMER_ID,EVENTO_ID,EVENTO,PRODUCTO_ID,PRODUCTO,PROD_CATEGORY_ID,PROD_CATEGORY,FECHA,REASON,DATE_EXP
4463,12949,108,"Upgrade or Downgrade, New Product",132,DIRECTV ORO MIX,3,Basico,2020-01-01 00:11:58,7046,202001
4964,12949,107,"Upgrade or Downgrade, Old Product",139,DIRECTV ORO HD ONLY,3,Basico,2020-01-01 00:11:58,7045,202001
4591,29640,108,"Upgrade or Downgrade, New Product",134,DIRECTV ORO HD DVR,3,Basico,2020-01-09 13:59:52,7046,202001
4965,29640,107,"Upgrade or Downgrade, Old Product",139,DIRECTV ORO HD ONLY,3,Basico,2020-01-09 13:59:52,7045,202001
4602,30728,108,"Upgrade or Downgrade, New Product",135,DIRECTV ACCESS MIX,3,Basico,2020-01-01 00:11:24,7046,202001

In [29]:
df_prod_change=df_prod_change.groupby('CUSTOMER_ID').head(2)

In [30]:
old=df_prod_change.loc[df_prod_change.EVENTO_ID==107]
new=df_prod_change.loc[df_prod_change.EVENTO_ID==108]
movs=pd.merge(old,new,on="CUSTOMER_ID",how="left")

In [34]:
movs=movs[["CUSTOMER_ID","PRODUCTO_x","PRODUCTO_y"]]

      CUSTOMER_ID             PRODUCTO_x             PRODUCTO_y
0           12949    DIRECTV ORO HD ONLY        DIRECTV ORO MIX
1           29640    DIRECTV ORO HD ONLY     DIRECTV ORO HD DVR
2           30728    DIRECTV ORO HD ONLY     DIRECTV ACCESS MIX
3           31732        DIRECTV ORO MIX    DIRECTV ORO HD ONLY
4           37682     DIRECTV ORO HD DVR    DIRECTV ORO HD ONLY
...           ...                    ...                    ...
1433     55019684    DIRECTV ORO HD ONLY     DIRECTV ACCESS MIX
1434     55076387    DIRECTV ORO HD ONLY     DIRECTV ACCESS MIX
1435     55182592  DIRECTV PLATA HD ONLY    DIRECTV ORO HD ONLY
1436     55306058    DIRECTV ORO HD ONLY     DIRECTV ACCESS MIX
1437     55376228          DIRECTV PLATA  DIRECTV PLATA HD ONLY

[1438 rows x 3 columns]